package se.customervalue.cvs.dependency.externalservice.iTextPDFGenerator.NewBiz;

public class NewBizText {
	// Introduction
	public static final String[] paragraph1 = {"Customer Value Newbiz focuses on new customers, sales trends and customer behavior over time.", "Customer Value Newbiz fokuserar på nya kunder, försäljningsutvecklingen och kundernas köpbeteende över tiden."};
	public static final String[] paragraph2 = {"Group Newbiz includes new customers. It is particularly interesting for the reason that the cost of acquiring new customers can be relatively high.", "Gruppen Newbiz omfattar nya kunder. Den är särskilt intressant av den anledningen att kostnaden för att skaffa nya kunder kan vara relativt hög."};
	public static final String[] paragraph3 = {"The report Newbiz is a complement to Customer Value Report, which reports the active customers köpprognoser. Köpprognoserna's prediction about how customers will buy in the future. This is made clear by the customers grouped into Premium, improvers, Degraders, Newbiz and Others.", "Rapporten Newbiz är ett komplement till Customer Value Report som redovisar de aktiva kundernas köpprognoser. Köpprognoserna är förutsägelse om hur kunderna kommer att köpa i framtiden. Det tydliggörs genom att kunderna grupperas i Premium, Improvers, Degraders, Newbiz och Others."};
	public static final String[] paragraph4 = {"The group Newbiz is a potential for future growth. This of course requires that new customers continue to buy. It is therefore not enough to examine how the new customers purchased on their first visit. An evaluation of the costs of acquiring new customers from search engines or other channels should be considered in the long-term köputvecklingen. Customer Value Newbiz provide the evidence necessary to make the important evaluation.", "I gruppen Newbiz finns en potential för framtida tillväxt. Det förutsätter givetvis att de nya kunderna fortsätter att köpa. Det räcker därför inte att undersöka hur de nya kunderna köpt vid sitt första besök. En utvärdering av kostnaderna för att skaffa nya kunder från sökmotorer eller andra kanaler bör göras mot den långsiktiga köputvecklingen. Customer Value Newbiz ger det underlag som behövs för att göra den viktiga utvärderingen."};
	public static final String[] paragraph5 = {"The report pages 3 and 4 show the new customer to its business, first reported in the number of customers and then in sales.", "I rapportens sid 3 och 4 redovisas de nya kundernas betydelse för verksamheten, först redovisat i antal kunder och därefter i försäljning."};
	public static final String[] paragraph6 = {"The following statements follow the purchasing loyalty of the customers who started buying a particular month. This report presents how they continued to buy for 3, 12 and 24 months after the initial purchase.", "Den följande redovisningen följer köptroheten hos de kunder som börjat köpa en viss månad. Här redovisar rapporten hur de fortsatt att köpa under 3, 12 och 24 månader efter det första köpet."};
	public static final String[] paragraph7 = {"The aim is to follow the trend of customers generated at different times. By division is as accurate as monthly are given good opportunities to relate to nykundsgrupp media campaigns, promotions or changes in the competitive situation.", "Syftet är att följa utvecklingen av kunder som genererats vid olika tillfällen. Genom att indelningen är så noggrann som månadsvis ges bra möjligheter att hänföra vare nykundsgrupp till mediakampanjer, erbjudanden eller förändringar i konkurrenssituationen."};
	public static final String[] paragraph8 = {"To report should be transparent, it is designed with graphs. The Annex also the precise numerical information used to produce the graphs.", "För att redovisningen ska vara överskådlig är den utformad med grafer. I bilagan finns även den exakta numeriska informationen som använts för att ta fram graferna."};

	// Nykundsackvisition
	public static final String[] title1 = {"Nykundsackvisition", "Nykundsackvisition"};
	public static final String[] paragraph9 = {"Displays development-acquisition, and new customers importance for the month sale. The graphs show how many new customers-acquisition generated for the respective month. See Annex Table 1.", "Här visas utvecklingen av ackvisitionen och de nya kundernas betydelse för månadens försäljning. Graferna redovisar hur många nya kunder som ackvisitionen genererat för respektive månad. Jämför bilaga tabell 1."};
	public static final String[] paragraph10 = {"The definition of the new customers are the ones who never before bought according to the available data. The diagram (Fig. 1) presents the monthly number of new customers (blue color) which bought First time of the month compared to the number of repeat (red color) that bought the same month. To clarify, show the lower graph (Fig. 2), the monthly rate of new customers as a percentage of the total number of buying customers. See Table 2.", "Definitionen av nya kunder är de som aldrig tidigare köpt enligt tillgängliga data. Det övre diagrammet (fig. 1) redovisar månad för månad antal nya kunder (blå färg) som köpte för första gången den månaden jämfört med antal återkommande (röd färg) som köpte samma månad. För att förtydliga visar det nedre diagrammet (fig. 2) den månadsvisa andelen nya kunder i procent av det totala antalet köpande kunder. Se tabell 2."};

	// Försäljning nya vs återkommande kunder per månad
	public static final String[] title2 = {"Sales new vs returning customers per month", "Försäljning nya vs återkommande kunder per månad"};
	public static final String[] paragraph11 = {"To show the importance that the new customers have total sales reported here the overall sales performance (amount) Breakdown of new and repeat customers.", "För att visa betydelsen som de nya kunderna har för den totala försäljningen redovisas här den sammanlagda försäljningsutvecklingen (belopp) fördelad på nya och återkommande kunder."};
	public static final String[] paragraph12 = {"The upper diagram (Fig. 3) reported monthly sales of SEK to new customers compared with recurring (red color). The blue color represents the new customer's first purchase during the month . The yellow color reports these customers additional purchase in the same month. So it is optional to consider the additional (yellow) purchases as sales to new customers or repeat sales. See Annex Table 1.", "Det övre diagrammet (fig. 3) redovisar månad för månad försäljning i SEK till nya kunder jämfört med återkommande (röd färg). Den blå färgen representerar de nya kundernas första köp under månaden. Den gula färgen redovisar dessa kunders tillkommande köp under samma månad. Det är alltså valfritt att betrakta de tillkommande (gula) köpen som nykundsförsäljning eller återkommande försäljning. Jämför bilaga tabell 1."};
	public static final String[] paragraph13 = {"Again, to clarify shows the lower graph (Fig. 4) the proportion of sales to new customers as a percentage of the total monthly sales. See Annex table 2", "Återigen, för att förtydliga visar det nedre diagrammet (fig. 4) andelen försäljning till nya kunder i procent av den totala månadsförsäljningen. Jämför bilaga tabell 2"};
	public static final String[] paragraph14 = {"Here is a text about how great it is to check on the average sales ...", "Här finns en text om hur bra det är att kolla på genomsnittsförsäljningen..."};
	public static final String[] paragraph15 = {"The five diagrams above gives you safely thoughts and ideas for how you can improve your business. Here are some tips and suggestions on questions to ask in order to get valuable information by examining them .", "De fem diagrammen ovan ger dig säkert tankar och idéer till hur du kan förbättra din verksamhet. Här några tips och förslag på frågor att ställa för att få ut värdefull kunskap genom att granska dem."};
	public static final String[] paragraph16 = {"The influx of new customers - and sales to them - as you expected? If it is less certain periods - what did you then or before then? What happened to the market?", "Är tillflödet av nya kunder - och försäljningen till dem - som du förväntat dig? Om det är färre vissa perioder - vad gjorde du då eller dessförinnan? Vad hände på marknaden?"};
	public static final String[] paragraph17 = {"Is the balance between new and repeat customers reasonable? During the early phases means new customers, usually more. If you manage to get customers to come back and buy for a long time, they may repeat customers increasingly importance. They are then simply for an increasing share of sales.", "Är balansen mellan nya och återkommande kunder rimlig? Under tidiga faser betyder nya kunder oftast mer. Lyckas du få kunderna att komma tillbaka och köpa under lång tid får de återkommande kunderna en allt större betydelse. De står då helt enkelt för en allt större del av försäljningen."};
	public static final String[] paragraph18 = {"You probably need to bring in new customers to your business will evolve as you wish. But it may be possible to develop the business also with existing customers. First, by selling more to each a. But also by ensuring that they remain customers. It gives a stronger effect of nykunds-raising. Your company develops simply faster. And will probably be more profitable.", "Du behöver förmodligen skaffa nya kunder för att ditt företag ska utvecklas som du önskar. Men det kan vara möjligt att utveckla verksamheten också med befintliga kunder. Dels genom att sälja mer till var och en. Men också genom att se till att de förblir kunder. Det ger en kraftigare effekt av nykunds-anskaffningen. Ditt företag utvecklas helt enkelt snabbare. Och blir förmodligen mer lönsamt."};
	public static final String[] paragraph19 = {"It is important to compare what it costs to buy a customer. Also, compare the cost of retaining an existing customer. An important question to ask is how long a customer needs purchase to be profitable.", "Viktigt är att jämföra vad det kostar att köpa en kund. Jämför också med kostnaden för att behålla en befintlig kund. En viktig fråga att ställa sig är under hur lång tid en kund behöver köpa för att bli lönsam."};

	// Försäljningsutveckling och köpbeteende
	public static final String[] title3 = {"Sales trends and buying behavior", "Försäljningsutveckling och köpbeteende"};
	public static final String[] paragraph20 = {"How the new customers continued to buy are shown in the following diagram where the report describes how the customers who bought the first time a month, nykundscohort, have returned with new purchase within 3, 12 and 24 months respectively. The report thus shows how the customers started to buy a particular month will continue to buy by reporting their purchases after the first month they bought.", "Hur de nya kunderna fortsatt att köpa visas av följande diagram där rapporten redovisar hur de kunder som köpt första gången en viss månad, ”nykundscohort”, har återkommit med nya köp inom 3, 12 respektive 24 månader. Rapporten visar alltså hur de kunder som börjat köpa en viss månad fortsätter att köpa genom att redovisa deras köp efter den första månaden de köpt. "};
	public static final String[] paragraph21 = {"The maximum repurchase period of 24 months, it is obviously only to show to the customers buying for the first time during the first twelve months of the combined reported period.", "Den längsta återköpsperioden, 24 månader, går det givetvis enbart att visa för de kunder som köpt för första gången under de första tolv månaderna av den sammanlagda redovisade perioden."};
	public static final String[] paragraph22 = {"The following diagram (Fig. 6) shows the percentage of customers who come back with purchases as a percentage. All the bars in a particular month, reports the following sales developments regarding the customers started buying it month . The red bar accounts for the proportion who returned with purchase within months. The green shows the repeat purchase within 12 months and the purple within 24 months. See Annex Tables 3a and 3b.", "Följande diagram (fig. 6) visar andelen kunder som återkommit med köp i procent. Samtliga staplar vid en viss månad redovisar den efterföljande försäljningsutvecklingen när det gäller de kunder som börjat köpa den månaden. Den röda stapeln redovisar andelen som återkommit med köp inom månader. Den gröna visar återkommande köp inom 12 månader och den lila inom 24 månader. Jämför bilaga tabell 3a och 3b."};
	public static final String[] paragraph23 = {"All new customers in a nykundscohort has obviously done a first purchase during his first month, that's why they qualify as new customers. But as the figure above shows there are relatively few who returned with further purchases during the first three months. This also means that the additional revenue (due to additional purchase) during the first three months is relatively low compared to the initial income from the respective nykundscohort.", "Alla nya kunder inom en nykundscohort har naturligtvis gjort ett ”första köp” under sin ”första månad”, det är ju därför de kvalificerar sig som nya kunder. Men som figuren ovan visar är det  relativt få som återkommit med ytterligare köp under de första tre månaderna. Detta betyder också att den tillkommande intäkten (på grund av ytterligare köp) under de första tre månaderna är relativt låg jämfört med den initiala intäkten från respektive nykundscohort."};
	public static final String[] paragraph24 = {"By evaluating each nykundscohort example, after three months, we get interesting information that shows the importance of new customers in different periods.", "Genom att utvärdera varje nykundscohort exempelvis efter tre månader får vi intressant information som visar vilken betydelse nya kunder har under olika perioder."};
	public static final String[] paragraph25 = {"• Overall revenues (after three months) consists of the new customers' first purchase and the additional revenue generated by the customers that already during the first few months returned with additional purchases.", "• Den sammanlagda intäkten (efter tre månader) utgörs av de nya kundernas ”första köp” samt de tillkommande intäkter som genererats av de kunder som redan under de första månaderna återkommit med ytterligare köp."};
	public static final String[] paragraph26 = {"• Once the evaluation is done already after three months is the new customer first purchase generally for most of the total revenue.", "• När utvärderingen görs redan efter tre månader står de nya kundernas ”första köp” vanligtvis för större delen av den sammanlagda intäkten."};
	public static final String[] paragraph27 = {"• The new customer repurchase - the amount of the additional revenues - is therefore usually a small part of the total revenue as relatively few customers will come back with further purchase in just three months.", "• De nya kundernas återköp – summan av de tillkommande intäkterna – utgör därför oftast en mindre del av den sammanlagda intäkten eftersom relativt få kunder återkommer med ytterligare köp redan inom tre månader"};
	public static final String[] paragraph28 = {"The following diagram (Fig. 7) shows the blue curve buyback share of total revenue in each nykundscohort, when the evaluation is done after three months.", "I nedanstående diagram (fig. 7) visar den blå kurvan återköpens andel av den sammanlagda intäkten inom respektive nykundscohort, när utvärderingen görs efter tre månader."};
	public static final String[] paragraph29 = {"Similarly, the red and green curve the buyback share of total revenue gradually increases in nykundscohorterna when the evaluation is done after 12 and 24 months. Compare table 3c.", "På motsvarande sätt visar den röda och gröna kurvan hur återköpens andel av den sammanlagda intäkten successivt ökar inom nykundscohorterna när utvärderingen görs efter 12 respektive 24 månader. Jämför tabell 3c."};
	public static final String[] paragraph30 = {"Here you can follow each nykundscohort (the customers started to buy a given month) from two aspects. How many purchases they have made and how much (amount) they bought after First month the customer has purchased. Again, the development of 3, 12 and 24 months respectively.", "Här kan du följa respektive nykundscohort (de kunder som börjat att köpa en viss månad) ur två aspekter. Hur många köp de gjort och hur mycket (belopp) de köpt för efter den första månaden kunden har köpt. Återigen visas utvecklingen inom 3, 12 respektive 24 månader. "};
	public static final String[] paragraph31 = {"Chart below (Fig. 8) shows the number of purchases. Each point on the horizontal line corresponds to the customers who started buying the month as the label indicates. The lines above the label shows how many purchases precisely those customers have made in each time interval. See Annex Table 4.", "Diagrammet nedan (fig. 8) visar antal köp. Varje punkt på den liggande linjen motsvarar de kunder som börjat köpa den månad som etiketten anger. På linjerna ovanför etiketten visas hur många köp just de kunderna gjort inom respektive tidsintervall. Jämför bilaga tabell 4."};
	public static final String[] paragraph32 = {"The diagram on the next page (Fig. 9) shows the development of sales in SEK. See Annex Table 5. Overall, the diagrams purchasing patterns of customers who started buying at different times. It may be valuable to address the differences with regard to the season and the campaigns that occurred at different times.", "Diagrammet på nästa sida (fig. 9) visar försäljningsutvecklingen i SEK. Jämför bilaga tabell 5. Sammantaget visar diagrammen köpbeteendet för de kunder som börjat köpa vid olika tidpunkter. Det kan vara värdefullt att beakta skillnader med tanke på säsong och de kampanjer som skett vid olika tidpunkter."};
	public static final String[] paragraph33 = {"The diagrams under the title \"Sales trends and buying behavior\" aims to be able to evaluate how loyal your new clients will be. The diagram presents what we call \" nykundscohorter \". This may be a little awkward in the beginning to read them. But more than well worth it to sit in.", "Diagrammen under rubriken \"Försäljningsutveckling och köpbeteende\" syftar till att du ska kunna utvärdera hur trogna dina nya kunder blir. Diagrammen redovisar det vi kallar \"nykundscohorter\". Det kan vara lite ovant i början att läsa sådana. Men mer än väl värt att sätta sig in i."};
	public static final String[] paragraph34 = {"Actually, it's simple. Each period (month) on the horizontal axis represents new customers purchasing for the first time that month. For each such period, you will see up to three tasks ( charts or points on a line). ", "Egentligen är det enkelt. Varje period (månad) på den liggande axeln motsvarar de nya kunder som köpte för första gången den månaden. För varje sådan period ser du upp till tre uppgifter (diagram eller punkter på en linje)."};
	public static final String[] paragraph35 = {"In the explanations for the colors used in each diagram, you see what they represent. They differ slightly between the figures.", "I förklaringarna till de färger som används i respektive diagram ser du vad de representerar. De skiljer sig lite åt mellan figurerna."};
	public static final String[] paragraph36 = {"Wisely is to examine the differences between the different periods.", "Klokt är att granska skillnader mellan de olika perioderna."};
	public static final String[] paragraph37 = {"• Is proportions similar month to month so behave your new customers in the same way regardless of when they started trading. It may suggest that you use the same way to acquire new customers. And that the season will not affect purchase behavior so much. A conclusion can therefore be - in this case - that casual customers buying such as Christmas shopping is not as important to your business. All this might suggest that all is well. But is it enough good? ", "• Är proportionerna likartade månad för månad så beter sig dina nya kunder på samma sätt oavsett när de började handla. Det kan tyda på att du använder samma sätt att skaffa nya kunder. Och att säsongen inte påverkar köpbeteendet så mycket. En slutsats kan alltså vara - i så fall - att tillfälliga kunder som köper till exempel i julhandeln inte är så betydande för din verksamhet. Allt det här kanske tyder på att allt är bra. Men är det tillräckligt bra?"};
	public static final String[] paragraph38 = {"• Are there differences between the months so it is worth thinking about why. Is it seasonal variations? Or is it because your activities on various occasions resulted in new clients with differing properties ? One trick is to simply draw in what activities you did and when. Perhaps also other events of importance. New competitors. Competitors changing prices and other offers. For example.", "• Är det skillnader mellan månaderna så är det värt att fundera på varför. Handlar det om säsongsvariationer? Eller beror det på att dina aktiviteter vid olika tillfällen resulterade i nya kunder med skilda egenskaper? Ett knep är att helt enkelt rita in vilka aktiviteter du gjorde och när. Kanske också andra händelser av vikt. Nya konkurrenter. Konkurrenters ändrade priser och andra erbjudande. Till exempel."};
	public static final String[] paragraph39 = {"Wise also examine how high the bars are compared with one another in Figure 6 (which shows the number of purchase). And the differences in income (Figure 7).", "Klokt är också att granska hur höga staplarna är jämfört med varandra i figur 6 (som visar antal köp). Och skillnaderna i intäkter (figur 7)."};
	public static final String[] paragraph40 = {"• You see quickly and easily how likely customers started to buy a given month were to buy again. Tend repurchases to be smaller or larger over time?", "• Du ser enkelt och snabbt hur benägna kunderna som börjat köpa en viss månad varit att köpa igen. Tenderar återköpen att bli mindre eller större över tiden?"};
	public static final String[] paragraph41 = {"• Charts 8 and 9 differs by showing purchases per customer in the number of respective SEK.", "• Diagram 8 och 9 skiljer sig genom att visa köp per kund i antal respektive SEK."};
	public static final String[] paragraph42 = {"• Whether you choose to start from the first or second pair of graphs are the important questions you should ask: \n Are you getting enough high repurchase rate to your customers becomes profitable enough . \n - Are there differences between the periods that you can learn from for the future nykundsackvisitionen to become more efficient and profitable?", "• Vare sig du väljer att utgå från de första eller andra paret diagram är de viktiga frågorna du bör ställa:\n- Får du tillräckligt hög återköpsfrekvens så att dina kunder blir lönsamma nog. \n - Finns det skillnader mellan perioderna som du kan ta lärdom av för att den framtida nykundsackvisitionen ska bli effektivare och lönsammare?"};
	public static final String[] paragraph43 = {"The questions are important to ask. For it is given - profitable customers also means more profitable business.", "Frågorna är viktiga att ställa. För det är givet - lönsammare kunder innebär också lönsammare företag."};
}
